### ISSUE TITLE
Will you make this 2.3-ish?

### ISSUE THREAD

**Issue by dingnz** [bauhouse/configuration#3]
Will this extension be updated for symphony 2.3?

**Comment by vlad-ghita** [comment]
It's working fine on 2.3.

Check [update](https://github.com/bauhouse/configuration/tree/update) branch.

**Comment by bauhouse** [comment]
Version 1.4 updates the extension for Symphony 2.3. Version 1.5 adds legend and label formatting and sets database fields as read-only to prevent inadvertently breaking the site with this extension.
